name: Release

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test
        id: test
        run: |
          echo ${{ github.event.repository }}
          echo ${{ github.event.repository.git_tags_url }}
          echo ${{ github.event.repository.tags_url }}
          echo ${{ github.repository.git_tags_url }}
          echo ${{ github.repository.tags_url }}
          echo ${{ github.repository }}
          echo ${{ github.event.workflow_run }}
          echo $GITHUB_REF
          echo ${GITHUB_REF##*/}

      - name: Echo Tag
        id: echo-tag
        run: 
          version=$(echo ${GITHUB_REF##*/} | sed 's/^v//')
          echo "sample_output=$version" >> $GITHUB_ENV

      - name: Echo Tag1
        id: echo-tag1
        run: 
          echo ${{ env.sample_output }}
